### PR TITLE
Add the ability to push classic ASP pages

### PR DESCRIPTION
**Pull request by hashneo**
While I know its outdated technology, many companies including mine will use classic ASP pages. Adding this change lets me push classic ASP applications to the server.

### CODE REVIEW

**Comment by hashneo** [comment]
Another option would be to allow the deploying app to publish a web.config to override the created one?

**Comment by mavenraven** [comment]
Hey @hashneo, thanks for the PR! Do you have a sample/demo app that you could point us at that we can use to test this change?

**Comment by hashneo** [comment]
Any simple asp hello world should work fine. You only need to create the single page and push that directory. :-)

Steven

**Comment by hashneo** [comment]
https://github.com/hashneo/asp2dotnet/tree/master/sample

This should work. 

Steven

**Comment by mavenraven** [comment]
Thanks! It's on our backlog to take a look at and add tests around. In the meantime, have you signed the CLA? (i.e.

All pull request authors must have a Contributor License Agreement (CLA) on-file with us. Please sign the appropriate CLA (individual or corporate).

When sending signed CLA please provide your github username in case of individual CLA or the list of github usernames that can make pull requests on behalf of your organization.
)

**Comment by hashneo** [comment]
If it's part of cloud foundry then yes. 

Steven

**Comment by emalm** [comment]
Dreddbot has its hooks in now, so I will close and reopen this PR, and on the reopen it will do its CLA check.

**Comment by benmoss** [comment]
@hashneo thanks! we've merged your work in along with a super basic ASP test app.

**Comment by hashneo** [comment]
Excellent!. Thx.

**Pull request merged**
